OPENAI_API_KEY = "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"

from langchain_community.document_loaders import WebBaseLoader

# List of URLs to scrape
urls = ['https://en.wikipedia.org/wiki/List_of_programs_broadcast_by_Sony_Entertainment_Television',
'https://en.wikipedia.org/wiki/Kavya_%E2%80%93_Ek_Jazbaa,_Ek_Junoon',
'https://en.wikipedia.org/wiki/Dabangii_%E2%80%93_Mulgii_Aayi_Re_Aayi',
'https://en.wikipedia.org/wiki/Shrimad_Ramayan',
'https://en.wikipedia.org/wiki/Mehndi_Wala_Ghar',
'https://en.wikipedia.org/wiki/Madness_Machayenge_%E2%80%93_India_Ko_Hasayenge',
'https://en.wikipedia.org/wiki/Superstar_Singer',
'https://en.wikipedia.org/wiki/Mahabharat_(1988_TV_series)',
'https://en.wikipedia.org/wiki/Krishna_(TV_series)',
'https://en.wikipedia.org/wiki/Sumit_Sambhal_Lega',
'https://en.wikipedia.org/wiki/Kya_Hadsaa_Kya_Haqeeqat',
'https://en.wikipedia.org/wiki/Bade_Bhaiyya_Ki_Dulhania',
'https://en.wikipedia.org/wiki/The_Drama_Company',
'https://en.wikipedia.org/wiki/Family_No.1_(TV_series)',
'https://en.wikipedia.org/wiki/Mahi_Way',
'https://en.wikipedia.org/wiki/Aathvaan_Vachan',
'https://en.wikipedia.org/wiki/Adaalat_(TV_series)',
'https://en.wikipedia.org/wiki/Aisa_Des_Hai_Mera_(TV_series)',
'https://en.wikipedia.org/wiki/Alpviram',
'https://en.wikipedia.org/wiki/Amber_Dhara',
'https://en.wikipedia.org/wiki/Anamika_(2012_TV_series)',
'https://en.wikipedia.org/wiki/Appnapan_%E2%80%93_Badalte_Rishton_Ka_Bandhan',
'https://en.wikipedia.org/wiki/Baat_Hamari_Pakki_Hai',
'https://en.wikipedia.org/wiki/Babul_Ka_Aangann_Chootey_Na',
'https://en.wikipedia.org/wiki/Barsatein_%E2%80%93_Mausam_Pyaar_Ka',
'https://en.wikipedia.org/wiki/Bayttaab_Dil_Kee_Tamanna_Hai',
'https://en.wikipedia.org/wiki/Bade_Acche_Lagte_Hain',
'https://en.wikipedia.org/wiki/Bade_Achhe_Lagte_Hain_2',
'https://en.wikipedia.org/wiki/Bade_Achhe_Lagte_Hain_3',
'https://en.wikipedia.org/wiki/Beyhadh',
'https://en.wikipedia.org/wiki/Beyhadh_2',
'https://en.wikipedia.org/wiki/Bhanwar_(1998_TV_series)',
'https://en.wikipedia.org/wiki/Bharat_Ka_Veer_Putra_%E2%80%93_Maharana_Pratap',
'https://en.wikipedia.org/wiki/Byaah_Hamari_Bahoo_Ka',
'https://en.wikipedia.org/wiki/C.A.T.S._(TV_series)',
'https://en.wikipedia.org/wiki/CID_(Indian_TV_series)',
'https://en.wikipedia.org/wiki/Chittod_Ki_Rani_Padmini_Ka_Johur',
'https://en.wikipedia.org/wiki/Chhanchhan',
'https://en.wikipedia.org/wiki/Chandragupta_Maurya_(2018_TV_series)',
'https://en.wikipedia.org/wiki/Dekha_Ek_Khwab',
'https://en.wikipedia.org/wiki/Desh_Ki_Beti_Nandini',
'https://en.wikipedia.org/wiki/Dhadkan_(TV_series)',
'https://en.wikipedia.org/wiki/Dhadkan_Zindaggi_Kii',
'https://en.wikipedia.org/wiki/Dil_Hi_Toh_Hai',
'https://en.wikipedia.org/wiki/Dil_Ki_Baatein_Dil_Hi_Jaane',
'https://en.wikipedia.org/wiki/Ek_Deewaana_Tha',
'https://en.wikipedia.org/wiki/Ek_Duje_Ke_Vaaste',
'https://en.wikipedia.org/wiki/Ek_Duje_Ke_Vaaste_2',
'https://en.wikipedia.org/wiki/Ek_Ladki_Anjaani_Si_(TV_series)',
'https://en.wikipedia.org/wiki/Ek_Mahal_Ho_Sapno_Ka_(TV_series)',
'https://en.wikipedia.org/wiki/Ekk_Nayi_Pehchaan',
'https://en.wikipedia.org/wiki/Ek_Rishta_Saajhedari_Ka',
'https://en.wikipedia.org/wiki/Ek_Safar_Aisa_Kabhi_Socha_Na_Tha',
'https://en.wikipedia.org/wiki/Encounter_(Indian_TV_series)',
'https://en.wikipedia.org/wiki/Ghar_Ek_Mandir_(TV_series)',
'https://en.wikipedia.org/wiki/Haasil_(Indian_TV_series)',
'https://en.wikipedia.org/wiki/Heena_(TV_series)',
'https://en.wikipedia.org/wiki/Hongey_Judaa_Na_Hum',
'https://en.wikipedia.org/wiki/Hubahu',
'https://en.wikipedia.org/wiki/Hum_Hain_Na',
'https://en.wikipedia.org/wiki/Hum_Ladkiyan',
'https://en.wikipedia.org/wiki/Hum_Pardesi_Ho_Gaye',
'https://en.wikipedia.org/wiki/Hum_Rahein_Na_Rahein_Hum',
'https://en.wikipedia.org/wiki/Humsafars',
'https://en.wikipedia.org/wiki/Indiawaali_Maa',
'https://en.wikipedia.org/wiki/Ishaaron_Ishaaron_Mein_(TV_Series)',
'https://en.wikipedia.org/wiki/Ishk_Par_Zor_Nahi',
'https://en.wikipedia.org/wiki/Itna_Karo_Na_Mujhe_Pyaar',
'https://en.wikipedia.org/wiki/Jaane_Kahan_Mera_Jigar_Gaya_Ji',
'https://en.wikipedia.org/wiki/Jaat_Ki_Jugni',
'https://en.wikipedia.org/wiki/Jagannath_Aur_Purvi_Ki_Dosti_Anokhi',
'https://en.wikipedia.org/wiki/Jassi_Jaissi_Koi_Nahin',
'https://en.wikipedia.org/wiki/Jeet_Jayenge_Hum',
'https://en.wikipedia.org/wiki/Just_Mohabbat',
'https://en.wikipedia.org/wiki/Kaajjal',
'https://en.wikipedia.org/wiki/Kaamnaa',
'https://en.wikipedia.org/wiki/Kabhie_To_Nazar_Milao',
'https://en.wikipedia.org/wiki/Kahani_Terrii_Merrii',
'https://en.wikipedia.org/wiki/Kahin_Diyaa_Jale_Kahin_Jiyaa',
'https://en.wikipedia.org/wiki/Kaisa_Ye_Pyar_Hai',
'https://en.wikipedia.org/wiki/Katha_Ankahee',
'https://en.wikipedia.org/wiki/Karamchand',
'https://en.wikipedia.org/wiki/Kehta_Hai_Dil_Jee_Le_Zara',
'https://en.wikipedia.org/wiki/Kkehna_Hai_Kuch_Mujhko',
'https://en.wikipedia.org/wiki/Khotey_Sikkey',
'https://en.wikipedia.org/wiki/Kismat_(TV_series)',
'https://en.wikipedia.org/wiki/Kkoi_Dil_Mein_Hai',
'https://en.wikipedia.org/wiki/Krishnaben_Khakhrawala',
'https://en.wikipedia.org/wiki/Kuch_Rang_Pyar_Ke_Aise_Bhi',
'https://en.wikipedia.org/wiki/Kuch_Rang_Pyar_Ke_Aise_Bhi:_Nayi_Kahaani',
'https://en.wikipedia.org/wiki/Kuchh_Jhuki_Palkain',
'https://en.wikipedia.org/wiki/Kuch_Toh_Log_Kahenge',
'https://en.wikipedia.org/wiki/Kuchh_Is_Tara',
'https://en.wikipedia.org/wiki/Kkusum',
'https://en.wikipedia.org/wiki/Kulvaddhu',
'https://en.wikipedia.org/wiki/Kutumb_(TV_series)',
'https://en.wikipedia.org/wiki/Kya_Huaa_Tera_Vaada',
'https://en.wikipedia.org/wiki/Kyun_Utthe_Dil_Chhod_Aaye',
'https://en.wikipedia.org/wiki/Love_Marriage_Ya_Arranged_Marriage',
'https://en.wikipedia.org/wiki/Maan_Rahe_Tera_Pitaah',
'https://en.wikipedia.org/wiki/Mahayagya',
'https://en.wikipedia.org/wiki/Main_Maike_Chali_Jaungi_Tum_Dekhte_Rahiyo',
'https://en.wikipedia.org/wiki/Main_Naa_Bhoolungi',
'https://en.wikipedia.org/wiki/Man_Mein_Hai_Visshwas',
'https://en.wikipedia.org/wiki/Mere_Dad_Ki_Dulhan',
'https://en.wikipedia.org/wiki/Milan_(Indian_TV_series)',
'https://en.wikipedia.org/wiki/Mooh_Boli_Shaadi',
'https://en.wikipedia.org/wiki/Mose_Chhal_Kiye_Jaaye',
'https://en.wikipedia.org/wiki/Par_Is_Dil_Ko_Kaise_Samjaye',
'https://en.wikipedia.org/wiki/Prithvi_Vallabh_-_Itihaas_Bhi,_Rahasya_Bhi',
'https://en.wikipedia.org/wiki/Parvarrish_%E2%80%93_Kuchh_Khattee_Kuchh_Meethi',
'https://en.wikipedia.org/wiki/Parvarrish_-_Season_2',
'https://en.wikipedia.org/wiki/Pehredaar_Piya_Ki',
'https://en.wikipedia.org/wiki/Peshwa_Bajirao_(TV_series)',
'https://en.wikipedia.org/wiki/Patiala_Babes',
'https://en.wikipedia.org/wiki/Porus_(TV_series)',
'https://en.wikipedia.org/wiki/Powder_(TV_series)',
'https://en.wikipedia.org/wiki/Punyashlok_Ahilyabai',
'https://en.wikipedia.org/wiki/Pyaar_Ka_Bandhan',
'https://en.wikipedia.org/wiki/Pyaar_Ko_Ho_Jaane_Do',
'https://en.wikipedia.org/wiki/Reporters_(Indian_TV_Series)',
'https://en.wikipedia.org/wiki/Rihaee_(TV_series)',
'https://en.wikipedia.org/wiki/Rishta.com',
'https://en.wikipedia.org/wiki/Rishta_Likhenge_Hum_Naya',
'https://en.wikipedia.org/wiki/Risshton_Ki_Dor',
'https://en.wikipedia.org/wiki/Saaksshi',
'https://en.wikipedia.org/wiki/Saas_Bina_Sasural',
'https://en.wikipedia.org/wiki/Saaya_(Indian_TV_series)',
'https://en.wikipedia.org/wiki/Sambhav_Asambhav',
'https://en.wikipedia.org/wiki/Sapnon_Ki_Chhalaang',
'https://en.wikipedia.org/wiki/Shaheen_(TV_series)',
'https://en.wikipedia.org/wiki/Shubh_Vivah',
'https://en.wikipedia.org/wiki/Specials_@_10',
'https://en.wikipedia.org/wiki/Story_9_Months_Ki',
'https://en.wikipedia.org/wiki/Sujata_(TV_series)',
'https://en.wikipedia.org/wiki/Sukh_By_Chance',
'https://en.wikipedia.org/wiki/Tara_From_Satara',
'https://en.wikipedia.org/wiki/Tera_Mujhse_Hai_Pehle_Ka_Naata_Koi',
'https://en.wikipedia.org/wiki/Thoda_Hai_Thode_Ki_Zaroorat_Hai',
'https://en.wikipedia.org/wiki/Thodi_Khushi_Thode_Gham',
'https://en.wikipedia.org/wiki/Tujko_Hai_Salaam_Zindgi',
'https://en.wikipedia.org/wiki/Tum_Aise_Hi_Rehna',
'https://en.wikipedia.org/wiki/Vaidehi_(2006_TV_series)',
'https://en.wikipedia.org/wiki/Virrudh',
'https://en.wikipedia.org/wiki/Waqt_Batayega_Kaun_Apna_Kaun_Paraya',
'https://en.wikipedia.org/wiki/Ye_Meri_Life_Hai',
'https://en.wikipedia.org/wiki/Yeh_Moh_Moh_Ke_Dhaagey',
'https://en.wikipedia.org/wiki/Yeh_Pyaar_Nahi_Toh_Kya_Hai',
'https://en.wikipedia.org/wiki/Yeh_Un_Dinon_Ki_Baat_Hai',
'https://en.wikipedia.org/wiki/Yudh_(TV_series)',
'https://en.wikipedia.org/wiki/Achanak_37_Saal_Baad',
'https://en.wikipedia.org/wiki/Aahat_(Indian_TV_series)',
'https://en.wikipedia.org/wiki/Bhoot_Aaya',
'https://en.wikipedia.org/wiki/Devi_(TV_series)',
'https://en.wikipedia.org/wiki/Seven_(TV_series)',
'https://en.wikipedia.org/wiki/Jai_Veer_Hanuman',
'https://en.wikipedia.org/wiki/Sankatmochan_Mahabali_Hanuman',
'https://en.wikipedia.org/wiki/Shree_Ganesh',
'https://en.wikipedia.org/wiki/Suryaputra_Karn',
'https://en.wikipedia.org/wiki/Vighnaharta_Ganesha',
'https://en.wikipedia.org/wiki/Yashomati_Maiyaa_Ke_Nandlala',
'https://en.wikipedia.org/wiki/Mere_Sai_-_Shraddha_Aur_Saburi',
'https://en.wikipedia.org/wiki/10_Ka_Dum',
'https://en.wikipedia.org/wiki/Bigg_Boss',
'https://en.wikipedia.org/wiki/Boogie_Woogie_(Indian_TV_series)',
'https://en.wikipedia.org/wiki/Boogie_Woogie_Kids_Championship',
'https://en.wikipedia.org/wiki/Bournvita_Quiz_Contest',
'https://en.wikipedia.org/wiki/Box_Cricket_League',
'https://en.wikipedia.org/wiki/Bura_Na_Mano_Holi_Hai',
'https://en.wikipedia.org/wiki/Comedy_Circus',
'https://en.wikipedia.org/wiki/Dance_Premier_League',
'https://en.wikipedia.org/wiki/Deal_Ya_No_Deal',
'https://en.wikipedia.org/wiki/Dekh_India_Dekh',
'https://en.wikipedia.org/wiki/Eating_Out_(TV_series)',
'https://en.wikipedia.org/wiki/Entertainment_Ke_Liye_Kuch_Bhi_Karega',
'https://en.wikipedia.org/wiki/Fame_Gurukul',
'https://en.wikipedia.org/wiki/Family_Time_With_Kapil_Sharma',
'https://en.wikipedia.org/wiki/Fear_Factor_India',
'https://en.wikipedia.org/wiki/Indian_Idol_Junior',
'https://en.wikipedia.org/wiki/India%27s_Best_Dancer',
'https://en.wikipedia.org/wiki/India%27s_Laughter_Champion',
'https://en.wikipedia.org/wiki/Iss_Jungle_Se_Mujhe_Bachao',
'https://en.wikipedia.org/wiki/Jeeto_Chappar_Phaad_Ke',
'https://en.wikipedia.org/wiki/K_For_Kishore',
'https://en.wikipedia.org/wiki/Kandy_Floss_(TV_series)',
'https://en.wikipedia.org/wiki/Kaun_Banega_Crorepati',
'https://en.wikipedia.org/wiki/Lift_Kara_De',
'https://en.wikipedia.org/wiki/Maa_Exchange',
'https://en.wikipedia.org/wiki/MasterChef_India_(Hindi_season_7)',
'https://en.wikipedia.org/wiki/Movers_%26_Shakers_(TV_series)'
 
]

# Initialize a list to hold all documents
set_doc = []

# Iterate over each URL and load the documents
for url in urls:
    loader = WebBaseLoader(url)
    docs = loader.load()
    set_doc.extend(docs)

# Now `all_docs` contains documents from all the URLs
print(f"Loaded {len(set_doc)} documents from {len(urls)} URLs.")

import pickle

# Save the all_docs list to a file
with open('set.pkl', 'wb') as f:
    pickle.dump(set_doc, f)

print("Documents have been saved to set.pkl")
